title: Manoverboard Boilerplate
description:
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-cloudcannon-schedule
sass:
  sass_dir: _sass
  style: compressed
collections_dir: collections
include: ["/_images"]

# CloudCannon Options
_options:
  image: # Front matter field
    uploads_dir: "uploads"
  content: # Content Editor and block Editable Regions
    uploads_dir: "uploads"

#cloudcannon:
  data: true

# CloudCannon Field Descriptions
_comments:
  title: This is the page title used for SEO.
  
_editables:
  content:
    format: p h2 h3 h4 h5 h6
    blockquote: true
    bold: true
    italic: true
    underline: true
    bulletedlist: true
    numberedlist: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true

# Collections (Custom Post Types)
collections:
  # general_pages:
  #   output: true
  #   _hide_content: true
  #   permalink: /:name
  #   sort_by:   

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
